spring:
  datasource:
    url: jdbc:mysql://localhost:3306/h
    username: root
    password: yhc1228
    driver-class-name: com.mysql.cj.jdbc.Driver
  api:
    clientId: QfTEijdvKk61bG_U8Vcq
    clientSecret: lV2OU6hmsX
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000